### ISSUE TITLE
Allow bool flags to work differently

### ISSUE THREAD

**Issue by Mattlau04** [XuaTheGrate/Flag-Parsing#10]
I couldn't find a way to summarize for the title, but it would be great if there was a way to make something like this
`!command 5` returns arg=False and `!command 5 --arg` returns arg=True (without having to do `!command 5 --arg true`)

**Comment by zomatree** [comment]
As ext.flags uses argparse to parse the args you can use the `"store_true"` action from [argparse](https://docs.python.org/3/library/argparse.html#action).

**Comment by Mattlau04** [comment]
Oh i didn't know, thanks!
