### ISSUE TITLE
Flag-Parsing is not up-to-date with discord.py

### ISSUE THREAD

**Issue by sairam4123** [XuaTheGrate/Flag-Parsing#12]
Flag-Parsing is not up-to-date with discord.py.

These're the changes I found:
1. discord.py rises specific errors, instead of BadArgument.

I'll update the issue, if I found some.

**Comment by XuaTheGrate** [comment]
Raising those errors would put the minimum required discord.py version at 1.5. For the time being, I want to be able to support 1.4.2 as gateway v6 is still alive. I'll leave this issue open as I want this behaviour to change in the future, or perhaps even use the built in converters to prevent this happening in the future, but for now I cannot think of a design to support all versions.

**Comment by sairam4123** [comment]
Well, I recommend making a separate branch, and update them, just merge the branch to master branch once the v6 gateway is down.

**Comment by XuaTheGrate** [comment]
Due to changes on discords end breaking all non-1.5 versions, it seems like this issue is good to solve in the future.

**Comment by sairam4123** [comment]
Yup, I would like to help as well.

**Comment by XuaTheGrate** [comment]
Fixed with #15
