### ISSUE TITLE
Support for Non-argument flags?

### ISSUE THREAD

**Issue by CircuitSacul** [XuaTheGrate/Flag-Parsing#16]
This is more of a question (and maybe a feature request), but does this support using flags without passing arguments? Instead of
```
!command --flag arg --boolflag yes --flag2 arg2
```
is it possible to do
```
!command --flag arg -boolflag --flag2 arg2
```

Also, I tried contacting you over discord, but it says that "Maya#0006" is not accepting friend requests, and I couldn't find you on any of the servers I'm in.

**Comment by XuaTheGrate** [comment]
Since this is a thin wrapper of ``argparse``, you can easily do whatever argparse does. As such, if you do
```python
@flags.add_flag("--boolflag", action="store_true")
```
it will work as intended.
