### ISSUE TITLE
Flags does not work well with optional arguments

### ISSUE THREAD

**Issue by webkaiyo** [XuaTheGrate/Flag-Parsing#19]
`@flags.command()` tries to parse commands arguments first. This causes the library to interpret flags as parameters when it shouldn't happen.

Code (relevant part):
```py
@flags.command(aliases=['purge'])
@flags.add_flag('--user', type=discord.User, nargs='+')
@flags.add_flag('--contains', type=str, nargs='+')
... # another flags
@flags.add_flag('--after', type=int)
@flags.add_flag('--before', type=int)
async def clear(self, ctx: commands.Context, amount: int=100, **flags):
  ...
```

Command invocation:
```
!clear --after=<random_id_here>
```

Exception:
```
discord.ext.commands.errors.BadArgument: Converting to "int" failed for parameter "amount".
```

**Comment by InterStella0** [comment]
This isn't a bug, this is discord.py default's error, this happens because `--after`  isn't a number and it tries to convert it. This is irrelevant to the flag library. Consider using `typing.Optional` if you want to silent it.
