### ISSUE TITLE
Aliases for flags

### ISSUE THREAD

**Issue by gustavwilliam** [XuaTheGrate/Flag-Parsing#8]
Often times, I want to be able to use both "--message" and "-m" as flags for the same functionality. The way that aliases are added for commands would probably be the best way to implement it for the flags as well:
`@flags.add_flag("--message", aliases=["-m"], type=str)`

**Comment by XuaTheGrate** [comment]
This functionality is already available, you can simply do `@flags.add_flag('-m', '--message', type=str)` and that will add both `-m` and `--message` to the target flag.
To access the flag further in the command, you use `flags['message']`.
