### ISSUE TITLE
Allow the use of a regular optional argument

### ISSUE THREAD

**Issue by Mattlau04** [XuaTheGrate/Flag-Parsing#9]
i want to use a command that goes something like that: `!command arg --flag1 "arg 1" --flag2 "arg 2"` , but with the arg being an optional argument.
I tried the normal way `async def command(self, ctx, arg=1, **flags):`, but if the optional argument wasn't passed, all flags returned their default values
Then i tried `@flags.add_flag("args", default=None, nargs="+")`, but when invoking the command without the optional argument i get an ArgumentParsingError: the following arguments are required: args
So what would be nice is the ability to make the nargs="+" flag default to something, or at least add a way to have an optional argument

**Comment by XuaTheGrate** [comment]
``nargs`` here is a bit like how regex works; ``+`` means it requires one or more arguments.

You can use ``*`` to signify ``zero`` or more arguments, or ``?`` to signify an optional argument.
